name: "Sentinel Security Gate"

on: [push, pull_request]

jobs:
  check-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client code
        uses: actions/checkout@v4

      - name: Install Sentinel Engine
        env:
          TOKEN: ${{ secrets.SENTINEL_INSTALL_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
          python -m pip install --upgrade pip
          pip install git+https://github.com/DataWizual-Labs/Sentinel-Engine.git@main

      - name: Run Sentinel Analysis
        env:
          SENTINEL_ADMIN_REPO: "DataWizual-Labs/Sentinel-Engine"
          SENTINEL_ALERT_TOKEN: ${{ secrets.SENTINEL_INSTALL_TOKEN }}
          SENTINEL_CONFIG: "./sentinel.yaml"
        run: |
          sentinel scan .
