name: "Sentinel Security Gate"

on: [push, pull_request]

jobs:
  check-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client code
        uses: actions/checkout@v4

      - name: Install Sentinel Engine
        env:
          TOKEN: ${{ secrets.INSTALL_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
          python -m pip install --upgrade pip
          pip install git+https://github.com/DataWizual-Labs/Sentinel-Engine.git@main

      - name: Run Sentinel Analysis
        env:
          SENTINEL_ADMIN_REPO: ""
          SENTINEL_ALERT_TOKEN: ""
          SENTINEL_CONFIG: "./sentinel.yaml"
        run: |
          # Используем перенаправление потока (tee), чтобы видеть лог в консоли 
          # и одновременно сохранить его в файл, даже если команда завершится ошибкой.
          # 'set -o pipefail' гарантирует, что мы поймаем exit code от sentinel, а не от tee.
          set -o pipefail
          sentinel scan . | tee sentinel_report.txt

      - name: Upload Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-security-report
          path: sentinel_report.txt
          retention-days: 5
